CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL);
CREATE TABLE polls (id SERIAL PRIMARY KEY, qn TEXT, opts TEXT[2], oid INTEGER REFERENCES users(id), expire TIMESTAMP WITH TIME ZONE);
-- CREATE TABLE qns (id SERIAL PRIMARY KEY, pid INTEGER REFERENCES polls(id), qn TEXT, options TEXT[]);
